Traceback (most recent call last):
  File "/home/op/wzs/kts_guizhou_zuwang.py", line 63, in <module>
    relase_path = sys.argv[1]
IndexError: list index out of range
[Finish] Failed to deploy [103]