
PLAY [reco_release] ************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************
ok: [10.11.5.115]
ok: [10.11.5.111]
ok: [10.11.5.113]
ok: [10.11.5.112]
ok: [10.11.5.118]
ok: [10.11.5.117]
ok: [10.11.5.116]
ok: [10.11.5.119]
ok: [10.11.5.114]
ok: [10.11.5.122]
ok: [10.11.5.121]
ok: [10.11.5.120]
ok: [10.11.5.123]
ok: [10.11.5.124]
ok: [10.11.5.125]
ok: [10.11.5.126]
ok: [10.11.5.127]
ok: [10.11.5.128]
ok: [10.11.5.130]
ok: [10.11.5.129]
ok: [10.11.5.131]
ok: [10.11.5.132]
ok: [10.11.5.133]
ok: [10.11.5.134]

TASK [reco_release : pull reco images 123456] **********************************************************************************************************************************************************************************************
fatal: [10.11.5.113]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.274195", "end": "2018-11-14 11:01:26.849950", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:23.575755", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.112]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.429605", "end": "2018-11-14 11:01:26.981877", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:23.552272", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.111]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.447157", "end": "2018-11-14 11:01:26.994901", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:23.547744", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.115]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.562778", "end": "2018-11-14 11:01:27.152527", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:23.589749", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.114]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.613128", "end": "2018-11-14 11:01:27.179783", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:23.566655", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.116]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.428318", "end": "2018-11-14 11:01:30.637194", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:27.208876", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.118]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.280913", "end": "2018-11-14 11:01:30.675519", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:27.394606", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.119]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.319879", "end": "2018-11-14 11:01:30.787299", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:27.467420", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.120]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.327009", "end": "2018-11-14 11:01:30.826883", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:27.499874", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.117]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.897204", "end": "2018-11-14 11:01:31.215916", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:27.318712", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.122]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.288814", "end": "2018-11-14 11:01:34.241384", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:30.952570", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.121]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.356508", "end": "2018-11-14 11:01:34.309456", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:30.952948", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.123]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.290505", "end": "2018-11-14 11:01:34.316810", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:31.026305", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.125]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.387000", "end": "2018-11-14 11:01:34.917310", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:31.530310", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.124]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:04.467857", "end": "2018-11-14 11:01:35.538125", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:31.070268", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.126]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.433575", "end": "2018-11-14 11:01:38.042797", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:34.609222", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.127]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.399826", "end": "2018-11-14 11:01:38.048607", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:34.648781", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.128]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.469051", "end": "2018-11-14 11:01:38.207181", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:34.738130", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.129]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.602303", "end": "2018-11-14 11:01:38.758001", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:35.155698", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.130]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.223027", "end": "2018-11-14 11:01:39.092720", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:35.869693", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.132]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.292729", "end": "2018-11-14 11:01:41.677368", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:38.384639", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.131]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.353386", "end": "2018-11-14 11:01:41.726795", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:38.373409", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.133]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.355585", "end": "2018-11-14 11:01:41.851742", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:38.496157", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.134]: FAILED! => {"changed": true, "cmd": "docker pull 123456", "delta": "0:00:03.302121", "end": "2018-11-14 11:01:42.438921", "msg": "non-zero return code", "rc": 1, "start": "2018-11-14 11:01:39.136800", "stderr": "Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 123456, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
	to retry, use: --limit @/home/op/cheng/autohdmap_deploy/reco_release.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
10.11.5.111                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.112                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.113                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.114                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.115                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.116                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.117                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.118                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.119                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.120                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.121                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.122                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.123                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.124                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.125                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.126                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.127                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.128                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.129                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.130                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.131                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.132                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.133                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.134                : ok=1    changed=0    unreachable=0    failed=1   

[Finish] Failed to deploy [123456]