
PLAY [reco_release] **************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************
ok: [10.11.5.114]
ok: [10.11.5.111]
ok: [10.11.5.115]
ok: [10.11.5.112]
ok: [10.11.5.113]
ok: [10.11.5.116]
ok: [10.11.5.117]
ok: [10.11.5.118]
ok: [10.11.5.119]
ok: [10.11.5.120]
ok: [10.11.5.121]
ok: [10.11.5.124]
ok: [10.11.5.123]
ok: [10.11.5.125]
ok: [10.11.5.122]
ok: [10.11.5.126]
ok: [10.11.5.127]
ok: [10.11.5.128]
ok: [10.11.5.129]
ok: [10.11.5.130]
ok: [10.11.5.131]
ok: [10.11.5.132]
ok: [10.11.5.133]
ok: [10.11.5.134]

TASK [reco_release : pull reco images 321] ***************************************************************************************
fatal: [10.11.5.112]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:03.889122", "end": "2018-10-26 16:04:56.957696", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:53.068574", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.114]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:03.915604", "end": "2018-10-26 16:04:57.108997", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:53.193393", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.115]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:03.854860", "end": "2018-10-26 16:04:56.977943", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:53.123083", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.111]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:03.999142", "end": "2018-10-26 16:04:57.031452", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:53.032310", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.113]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.504294", "end": "2018-10-26 16:04:57.573669", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:53.069375", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.118]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:03.901741", "end": "2018-10-26 16:05:01.378055", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:57.476314", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.117]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.302399", "end": "2018-10-26 16:05:01.680014", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:57.377615", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.120]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.155252", "end": "2018-10-26 16:05:02.140090", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:57.984838", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.116]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:05.389838", "end": "2018-10-26 16:05:02.701371", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:57.311533", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.119]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:05.296052", "end": "2018-10-26 16:05:02.879484", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:04:57.583432", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.121]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.190875", "end": "2018-10-26 16:05:05.880191", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:01.689316", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.122]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.394808", "end": "2018-10-26 16:05:06.372858", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:01.978050", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.123]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.408100", "end": "2018-10-26 16:05:06.853571", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:02.445471", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.124]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.243008", "end": "2018-10-26 16:05:07.261475", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:03.018467", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.125]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:05.304598", "end": "2018-10-26 16:05:08.550732", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:03.246134", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.126]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.318962", "end": "2018-10-26 16:05:10.607752", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:06.288790", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.127]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.365355", "end": "2018-10-26 16:05:11.146294", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:06.780939", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.128]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.311610", "end": "2018-10-26 16:05:11.560825", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:07.249215", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.129]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.620903", "end": "2018-10-26 16:05:12.286314", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:07.665411", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.130]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.253047", "end": "2018-10-26 16:05:13.192171", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:08.939124", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.132]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.229257", "end": "2018-10-26 16:05:15.678550", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:11.449293", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.133]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:04.105117", "end": "2018-10-26 16:05:16.019957", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:11.914840", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.131]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:06.179185", "end": "2018-10-26 16:05:17.149783", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:10.970598", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
fatal: [10.11.5.134]: FAILED! => {"changed": true, "cmd": "docker pull 321", "delta": "0:00:05.265434", "end": "2018-10-26 16:05:17.849343", "msg": "non-zero return code", "rc": 1, "start": "2018-10-26 16:05:12.583909", "stderr": "Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for 321, repository does not exist or may require 'docker login'"], "stdout": "Using default tag: latest", "stdout_lines": ["Using default tag: latest"]}
	to retry, use: --limit @/home/kddev/cheng/autohdmap_deploy/reco_release.retry

PLAY RECAP ***********************************************************************************************************************
10.11.5.111                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.112                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.113                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.114                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.115                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.116                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.117                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.118                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.119                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.120                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.121                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.122                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.123                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.124                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.125                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.126                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.127                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.128                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.129                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.130                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.131                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.132                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.133                : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.134                : ok=1    changed=0    unreachable=0    failed=1   

[Finish] Failed to deploy [321]